# Builds js/EmbeddedAssets.js — base64 data-URI bundle of the character model,
# animations and skins so the game runs with no XHR (file:// friendly).
$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$out = Join-Path $root "js\EmbeddedAssets.js"

function B64([string]$path) {
    $bytes = [System.IO.File]::ReadAllBytes($path)
    return [System.Convert]::ToBase64String($bytes)
}

$lines = @()
$lines += '"use strict";'
$lines += ''
$lines += '// GENERATED by scripts/build-embedded.ps1 — do not edit by hand.'
$lines += '// Base64 data-URIs of the CC0 Kenney character assets (see Assets/characters/License.txt).'
$lines += 'const EmbeddedAssets = {'

$model = Join-Path $root "Assets\characters\Model\characterMedium.fbx"
$lines += '  model: "data:application/octet-stream;base64,' + (B64 $model) + '",'
$lines += '  anims: {'
foreach ($a in @("idle", "run", "jump")) {
    $p = Join-Path $root "Assets\characters\Animations\$a.fbx"
    $lines += "    ${a}: `"data:application/octet-stream;base64," + (B64 $p) + '",'
}
$lines += '  },'
$lines += '  skins: {'
foreach ($s in @("criminalMaleA", "cyborgFemaleA", "skaterFemaleA", "skaterMaleA")) {
    $p = Join-Path $root "Assets\characters\Skins\$s.png"
    $lines += "    ${s}: `"data:image/png;base64," + (B64 $p) + '",'
}
$lines += '  },'
$lines += '};'

[System.IO.File]::WriteAllText($out, ($lines -join "`r`n") + "`r`n")
Write-Output ("Wrote {0} ({1:N1} KB)" -f $out, ((Get-Item $out).Length / 1KB))
